---
apiVersion: v1
kind: Service
metadata:
  name: sessions
  labels:
    visualize: "true"
    name: sessions
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    role: sessions-server
  type: LoadBalancer