apiVersion: v1
kind: Pod
metadata:
  name: "game-1234"
spec:
  hostNetwork: true
  restartPolicy: Never
  containers:
    - name: soccer-server
      image: gcr.io/unity-1355/soccer-server:0.1
      ports:
        - containerPort: 7777
          protocol: UDP
          hostPort: 7777
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP