resources:
- name: soccer-us-west
  type: container.v1.cluster
  properties:
    zone: us-west1-b
    cluster:
      name: soccer-us-west
      description: US West side server for soccer multiplayer
      nodePools:
        - name: "apps"
          initialNodeCount: 3
          config:
            machineType: n1-standard-2
            labels:
              role: apps
            oauthScopes:
              - https://www.googleapis.com/auth/devstorage.read_only
        - name: "game-servers"
          initialNodeCount: 4
          config:
            machineType: n1-standard-4
            tags:
              - game-server
            labels:
              role: game-server
            oauthScopes:
              - https://www.googleapis.com/auth/devstorage.read_only
      masterAuth:
        username: admin
        password: supersecret
- name: game-server-firewall
  type: compute.v1.firewall
  properties:
    name: game-server
    targetTags:
      - "game-server"
    allowed:
      - IPProtocol: udp
        ports:
          - "7000-8000"